### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [cyberjunky/python-garminconnect-ha#2]
It would be very helpful if you could tag releases as well. This would enable distributions to get the source from GitHub.

Thanks

**Comment by cyberjunky** [comment]
Can you elaborate?
As far as I know i have tagged the versions, do you mean something else?

**Comment by fabaff** [comment]
The latest release on PyPI is [0.1.7](https://pypi.org/project/garminconnect-ha/0.1.7/) but the latest tag is [0.1.6](https://github.com/cyberjunky/python-garminconnect-ha/releases/tag/0.1.6).
